### ISSUE TITLE
extend sharding metadata

### ISSUE THREAD

**Issue by no1seman** [tarantool/ddl#55] opened 2021-03-26 13:48 UTC
As for now ddl module creates _ddl_sharding_key space which contains only sharding key fileds but it's not enough for automatic data manipulation? for example by crud module. Need to add also the following data:
1. array of space fields which is used in sharding function to calculate sharding_key.
2. ability to store custom sharding function.

**Comment by rosik** [comment] 2021-03-29 15:49
As we discussed orally, p. 1 already exists - it's `sharding_key`. The misunderstanding was initially caused by migrations readme which we fixed in https://github.com/tarantool/migrations/pull/41

**Comment by no1seman** [comment] 2021-03-29 15:56
@rosik p. 1 is OK, it's rather a problem of migrations module , see this: https://github.com/tarantool/migrations/blob/b71511fb9b59c69040a1176a1aa9f2811ac347b1/migrator/utils.lua#L19
but p. 2 is still here ans seems that it must be solved someday

**Comment by Totktonada** [comment] 2021-10-01 02:31
The second point should be solved in #71. I propose to track and discuss it in #71 and, it seems, there is nothing more to track there. I'll close this issue. Feel free to reopen if I missed something.

**Closed by Totktonada** 2021-10-01 02:31 UTC
Labels: analysis
